AEANTI_BANDING: 2
AEANTI_BANDING_DEFAULT: 1
AE_LOCK: false
AWB_LOCK: false
AWB_LOCK_DEFAULT: false
EDGE_ENHANCE: 0
EDGE_ENHANCE_DEFAULT: 0
EXPOSURE_COMPENSATION: 0.0
EXPOSURE_COMPENSATION_DEFAULT: 0.0
SATURATION: 1.0
SATURATION_DEFAULT: 1.0
TNR_MODE: 1
TNR_MODE_DEFAULT: 1
WBMODE: 1
WBMODE_DEFAULT: 1
