CLOUD_STREAM_KEY: sk_ap-northeast-1_TFQVDKAsCWYn_ZK5ClG4HxOgSG8WaDyPGicl5upYRbD
CLOUD_URL_RTMP: rtmp://39e423d77154.global-contribute.live-video.net/app/
CLOUD_URL_RTMPS: rtmps://39e423d77154.global-contribute.live-video.net:443/app/
CROP_HEIGHT: 0
CROP_WIDTH: 425
DROP_LOCATION: /media/giocam3d/GIOVIEW/Recordings/
ENABLE_4K_STREAM: false
ENABLE_CAMERA_SETTINGS: true
FPS: 15
FRAME_HEIGHT: 2160
FRAME_WIDTH: 3840
H264_REC_BITRATE: 50000000
H264_STREAM_4K_BITRATE: 20000000
H264_STREAM_BITRATE: 8500000
H265_REC_BITRATE: 80000000
HFOV: 174.6
INTERPOLATION: Smart
QP_RANGE_RECORD: 24,24:28,28:30,30
QP_RANGE_STREAM: 18,30:24,30:28,30
SOURCE_L: 1
SOURCE_R: 0
STREAM_URL_4K_MEDIALIVE: rtmp://13.42.150.162:1935/single/live
STREAM_URL_4K_MEDIALIVE_H265: rtmp://18.133.85.35:1935/live/kumu1
STREAM_URL_4K_WOWZA: rtmp://a5ad0a0ae96b.entrypoint.cloud.wowza.com/app-h52g05S8/378e5444
VFOV: 117.6
VR_ADDRESS: 192.168.1.106
YOUTUBE_STREAM_KEY: 060w-amru-566y-kys3-1t3h
YOUTUBE_URL: rtmp://a.rtmp.youtube.com/live2
h265_full_width: true
