ADMIN_IMAGE_SIZE: 100,100
AI_WINDOW_SIZE_X: 1208
AI_WINDOW_SIZE_Y: 795
BACKGROUNG_IMAGE: ui/New folder/background_image.png
CAMERA_SETTINGS_WINDOW_SIZE_X: 425
CAMERA_SETTINGS_WINDOW_SIZE_Y: 347
DIAL_SIZE: 200
GALLERY_WINDOW_SIZE_X: 464
GALLERY_WINDOW_SIZE_Y: 281
ICON_SIZE: 100
KEY_WINDOW_SIZE_X: 425
KEY_WINDOW_SIZE_Y: 508
MAIN_WINDOW_SIZE_Y: 152
MEDIA_WINDOW_SIZE: 351,335
PRESET_WINDOW_SIZE_X: 507
PRESET_WINDOW_SIZE_Y: 615
RECORD_WINDOW_SIZE_X: 462
RECORD_WINDOW_SIZE_Y: 322
RIG_CONTROLLER_WINDOW_SIZE_X: 424
RIG_CONTROLLER_WINDOW_SIZE_Y: 573
SELECT_3D_PREVIEW_WINDOW_X: 886
SELECT_3D_PREVIEW_WINDOW_Y: 382
SETTINGS_WINDOW_SIZE_X: 346
SETTINGS_WINDOW_SIZE_Y: 376
STREAM_TEST_WINDOW_SIZE: 379,197
STREAM_WINDOW_MIN_X: 569
STREAM_WINDOW_MIN_Y: 382
STREAM_WINDOW_SIZE_X: 415
STREAM_WINDOW_SIZE_Y: 323
TIMER_SIZE: 60
