AI_WINDOW_SIZE_X: 1447
AI_WINDOW_SIZE_Y: 795
CAMERA_SETTINGS_WINDOW_SIZE_X: 658
CAMERA_SETTINGS_WINDOW_SIZE_Y: 614
DIAL_SIZE: 200
GALLERY_WINDOW_SIZE_X: 470
GALLERY_WINDOW_SIZE_Y: 250
ICON_SIZE: 120
KEY_WINDOW_SIZE_X: 425
KEY_WINDOW_SIZE_Y: 508
MAIN_WINDOW_SIZE_Y: 149
MEDIA_WINDOW_SIZE: 500,300
PRESET_WINDOW_SIZE_X: 507
PRESET_WINDOW_SIZE_Y: 615
RECORD_WINDOW_SIZE_X: 895
RECORD_WINDOW_SIZE_Y: 561
RIG_CONTROLLER_WINDOW_SIZE_X: 588
RIG_CONTROLLER_WINDOW_SIZE_Y: 668
SELECT_3D_PREVIEW_WINDOW_X: 477
SELECT_3D_PREVIEW_WINDOW_Y: 382
SETTINGS_WINDOW_SIZE_X: 563
SETTINGS_WINDOW_SIZE_Y: 504
STREAM_WINDOW_MIN_X: 569
STREAM_WINDOW_MIN_Y: 382
STREAM_WINDOW_SIZE_X: 623
STREAM_WINDOW_SIZE_Y: 460
TIMER_SIZE: 60
ADMIN_IMAGE_SIZE: 200,200
STREAM_TEST_WINDOW_SIZE: 200,200
BACKGROUNG_IMAGE: ui/New folder/background_image.png